### ISSUE TITLE
How to install torchaudio and use it on Gaudi device

### ISSUE THREAD

**Issue by toantruongcs** [HabanaAI/Setup_and_Install#2]
Hi Habana support,
I have created a DL1 instance on AWS, which includes 8 Gaudi devices. I use pre-built Docker images for installing. I found that there are no problems when using torch or torchvision. But, I cannot install and use torchaudio compatible with torch on this machine. It seems that torchaudio is not supported like torch or torchvision.
How to install torchaudio on Gaudi device? Do gaudi-pt-modules include torchaudio?

**Comment by greg-serochi** [comment]
Hi @toantruongcs, thanks for posting this question.   We'll research this and get back to you.   It may take a little longer for a response due to the holiday.

**Comment by greg-serochi** [comment]
Hi @toantruongcs, currently torchaudio is not supported in the Habana SynapseAI(R) Software Stack. 

The torch libraries we currently supported are:
torchvision
huggingface
Fairseq:  you can see the NLP model for an example [here](https://github.com/HabanaAI/Model-References/tree/master/PyTorch/nlp/nmt/fairseq) 
PyTorch-lightning: you can see the Unet2D model for an example [here](https://github.com/HabanaAI/Model-References/tree/master/PyTorch/computer_vision/segmentation/Unet)

**Comment by toantruongcs** [comment]
> Hi @toantruongcs, currently torchaudio is not supported in the Habana SynapseAI(R) Software Stack.
> 
> The torch libraries we currently support are: torchvision huggingface Fairseq: you can see the NLP model for an example [here](https://github.com/HabanaAI/Model-References/tree/master/PyTorch/nlp/nmt/fairseq) PyTorch-lightning: you can see the Unet2D model for an example [here](https://github.com/HabanaAI/Model-References/tree/master/PyTorch/computer_vision/segmentation/Unet)

**Comment by toantruongcs** [comment]
Hi @greg-serochi, Do you have a plan to support torchaudio?

**Comment by greg-serochi** [comment]
Hi @toantruongcs, we do not currently have plans to support torchaudio.  Right now our focus is mainly on Computer Vision and NLP based workloads

**Comment by toantruongcs** [comment]
Hi @greg-serochi, can I build torchaudio for using on Gaudi device by myself? Do you have tutorials to do that?

**Comment by greg-serochi** [comment]
Hi @toantruongcs, we don't have any collateral for torchaudio because it's not supported by Habana at this time.   We would not recommend doing this right now as there may be other dependencies that would not get this to work properly.
