### ISSUE TITLE
Python Tensorflow error  

### ISSUE THREAD

**Issue by krishnamouli2** [HabanaAI/Setup_and_Install#3]
i am trying to install Tensorflow on a Habana gaudi machine , this is error msg i get after i following documentation  to install Tensorflow 
${PYTHON} -c "import habana_frameworks.tensorflow as htf; print(htf.__version__)"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/gaudipoc3/.local/lib/python3.8/site-packages/habana_frameworks/tensorflow/__init__.py", line 12, in <module>
    from .sysconfig import __version__
  File "/home/gaudipoc3/.local/lib/python3.8/site-packages/habana_frameworks/tensorflow/sysconfig.py", line 12, in <module>
    from .lib_utils import libraries_location, get_includes_location, _mandatory_lib
  File "/home/gaudipoc3/.local/lib/python3.8/site-packages/habana_frameworks/tensorflow/lib_utils.py", line 20, in <module>
    import tensorflow as tf
ModuleNotFoundError: No module named 'tensorflow'

 ${PYTHON} -m pip list | grep habana
habana-tensorflow            1.2.0.585

**Comment by greg-serochi** [comment]
Hi @krishnamouli2 thanks for posting this question.  We'll take a look at respond.

**Comment by krishnamouli2** [comment]
thank you greg....... but i was able to run using docker but I m facing a new issue  sudo docker run -it --runtime=habana -e HABANA_VISIBLE_DEVICES=all -e OMPI_MCA_btl_vader_single_copy_mechanism=none --cap-add=sys_nice --net=host vault.habana.ai/gaudi-docker/1.2.0/ubuntu18.04/habanalabs/tensorflow-installer-tf-cpu-2.7.0:1.2.0-585
docker: Error response from daemon: Unknown runtime specified habana.

**Comment by greg-serochi** [comment]
did you load the container runtime?    https://docs.habana.ai/en/latest/Installation_Guide/GAUDI_Installation_Guide.html#container-runtime-installation

**Comment by krishnamouli2** [comment]
Yes i have loaded the container and did the configurations according to document still got the error

**Comment by krishnamouli2** [comment]
i am an error in the docker container.............i have run the journalctl -xe for the Habana container........................... The result is RESULT.
Feb 02 12:57:49 gaudipoc1 systemd[1]: containerd.service: Service hold-off time over, scheduling restart.
Feb 02 12:57:49 gaudipoc1 systemd[1]: containerd.service: Scheduled restart job, restart counter is at 2744.
-- Subject: Automatic restarting of a unit has been scheduled
-- Defined-By: systemd
-- Support: http://www.ubuntu.com/support
--
-- Automatic restarting of the unit containerd.service has been scheduled, as the result for
-- the configured Restart= setting for the unit.
Feb 02 12:57:49 gaudipoc1 systemd[1]: Stopped containerd container runtime.
-- Subject: Unit containerd.service has finished shutting down
-- Defined-By: systemd
-- Support: http://www.ubuntu.com/support
--
-- Unit containerd.service has finished shutting down.
Feb 02 12:57:49 gaudipoc1 systemd[1]: Starting containerd container runtime...
-- Subject: Unit containerd.service has begun start-up
-- Defined-By: systemd
-- Support: http://www.ubuntu.com/support
--
-- Unit containerd.service has begun starting up.
Feb 02 12:57:49 gaudipoc1 containerd[73216]: containerd: Near line 14 (last key parsed 'plugins.io.containerd.runtime.v1.linux')
Feb 02 12:57:49 gaudipoc1 systemd[1]: containerd.service: Main process exited, code=exited, status=1/FAILURE
Feb 02 12:57:49 gaudipoc1 systemd[1]: containerd.service: Failed with result 'exit-code'.
Feb 02 12:57:49 gaudipoc1 systemd[1]: Failed to start containerd container runtime.
-- Subject: Unit containerd.service has failed
-- Defined-By: systemd
-- Support: http://www.ubuntu.com/support
--
-- Unit containerd.service has failed.
--

**Comment by greg-serochi** [comment]
Hi @krishnamouli2, let's take a step back and baseline your environment

Are you on-premise or using AWS DL1 instance, if you are using DL1, what is the AMI name and Docker image you are trying? 
What is the type of Model that you are using? 
for the runtime it looks like you are using containerd, can you please send your `/etc/containerd/config.toml` file
Please make sure that you are following the install instructions here: https://docs.habana.ai/en/latest/Installation_Guide/GAUDI_Installation_Guide.html#containerd-setup

Finally, you can provide us the output of the Snapshot for Debug tool 
```
git clone https://github.com/HabanaAI/Snapshot_For_Debug
touch OUT_DOCKER.txt
python src/gather_info_docker.py --lite --cmd=<command_script> -s OUT_DOCKER.txt
```
post the generated tar file (gather_info_docker.tar.gz) after checking its contents

**Comment by krishnamouli2** [comment]
Hi Grey, I am not using an AWS account but an on-premises machine with 8 Gaudi processors and it is on Ubuntu 18.04 os currently..... any debugging you want me to run??

**Comment by greg-serochi** [comment]
Hi @krishnamouli2; can you do these two things?  
1. please send us the `/etc/containerd/config.toml` file  (assuming that you are using containerd and NOT using docker runtime)  If you are using docker runtime, please send the `/etc/docker/daemon.json` file
2. Please run the Snapshot for Debug tool
```
git clone https://github.com/HabanaAI/Snapshot_For_Debug
touch OUT_DOCKER.txt
python src/gather_info_docker.py --lite --cmd=<command_script> -s OUT_DOCKER.txt
```

**Comment by greg-serochi** [comment]
Hi @krishnamouli2 , just checking in, can we help?

**Comment by greg-serochi** [comment]
closing this issue for now.
